version: "3.3"
services:
  proxy:
    image: nginx:stable
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./fiit1/test.db:/myapp/fiit1/test.db
    environment:
      APP_CONFIG: 'production.cfg'

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    volumes:
    - ./db:/var/lib/postgresql/data
